### ISSUE TITLE
Splurty Meta Tag

### ISSUE THREAD

**Issue by rajsrai** [Scharmy/turbo-scram#1]
Add a meta tag to your `app/views/layouts/application.html.erb` file so your site looks good on mobile devices.
It should look like this:
`<meta name="viewport" content="width=device-width, initial-scale=1">`

**Comment by Scharmy** [comment]
Made changes to the application.html.erb
Added the meta tag 

![2019-07-02_0-20-53](https://user-images.githubusercontent.com/52262306/60482492-c73cfd80-9c5f-11e9-91a0-24a5aacc3b5b.png)
